concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ci:
    if: ${{ !cancelled() && ! failure() }}
    needs: dependabot
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: ${{ matrix.python-version }}
      - run: env | sort
      - run: make dev
      - env:
          CHAT_AZURE_API_BASE: ${{ secrets.CHAT_AZURE_API_BASE }}
          CHAT_AZURE_API_VERSION: ${{ secrets.CHAT_AZURE_API_VERSION }}
          CHAT_MAX_TOKENS: ${{ secrets.CHAT_MAX_TOKENS }}
          CHAT_MODEL: ${{ secrets.CHAT_MODEL }}
          CHAT_TEMPERATURE: ${{ secrets.CHAT_TEMPERATURE }}
          EMBEDDING_AZURE_API_BASE: ${{ secrets.CHAT_AZURE_API_BASE }}
          EMBEDDING_AZURE_API_VERSION: ${{ secrets.CHAT_AZURE_API_VERSION }}
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
        name: lint test docs and build
        run: make lint test docs build
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' && startsWith(github.head_ref, 'dependabot/pip/') }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Set up Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Set up Python with multiple versions.
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: |
            3.8
            3.9
            3.10
            3.11
      - name: Install pipenv using pipx
        run: pipx install pipenv
      - name: Generate constraints for all supported Python versions
        run: |
          CI= PYTHON_VERSION=3.8 make constraints
          CI= PYTHON_VERSION=3.9 make constraints
          CI= PYTHON_VERSION=3.10 make constraints
          CI= PYTHON_VERSION=3.11 make constraints
      - name: Push changes if applicable
        run: |
          if [[ -n `git status --porcelain` ]]; then
            git commit -a -m "build: Update constraints for dependabot."
            git push
          fi
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: python
          build-mode: none
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    # If the analyze step fails for one of the languages you are analyzing with
    # "We were unable to automatically build your code", modify the matrix above
    # to set the build mode to "manual" for that language. Then modify this step
    # to build your code.
    # ℹ️ Command-line programs to run using the OS shell.
    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
    - if: matrix.build-mode == 'manual'
      shell: bash
      run: |
        echo 'If you are using a "manual" build mode for one or more of the' \
          'languages you are analyzing, replace this with the commands to build' \
          'your code, for example:'
        echo '  make bootstrap'
        echo '  make release'
        exit 1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
