name: Release
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  contents: read
jobs:
  release:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine  #  better-exceptions(optional for debug)
      - name: Release please
        uses: googleapis/release-please-action@v4
        with:
          # The current PAT (personal access token) was created on 2024-08-05,
          # since the maximum validity of PAT is 1 year, you need to change the PAT before 2025-08-05.
          token: ${{ secrets.PAT }}
          release-type: simple


  package:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}
          release-type: node
      - name: test
        run: echo ${{ steps.release.outputs.release_created }}
      # - uses: actions/checkout@v4
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     cache: pip
      #     python-version: '3.10'
      # - run: env | sort
      # - run: make dev
      # - run: make build


      #   if: ${{ steps.release.outputs.release_created }}
      # - run: env | sort
      #   if: ${{ steps.release.outputs.release_created }}
      # - run: make dev
      #   if: ${{ steps.release.outputs.release_created }}
      # - run: make build
      #   if: ${{ steps.release.outputs.release_created }}
      # - env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      #   run: |
      #     make upload
